</sys/src/ape/config
OS=0568qv
all:
	pcc -I../cheapglk -D_POSIX_SOURCE -D_BSD_EXTENSION -D_PLAN9_SOURCE -c glk.c
	pcc -I../cheapglk -D_POSIX_SOURCE -D_BSD_EXTENSION -D_PLAN9_SOURCE -c emu.c
	pcc -I../cheapglk -D_POSIX_SOURCE -D_BSD_EXTENSION -D_PLAN9_SOURCE -o magnetic emu.$O glk.$O -lcheapglk
install:
	mk
	cp magnetic /$objtype/bin
clean:
	rm -f *.[$OS] [$OS].out y.tab.? lex.yy.c y.debug y.output $TARG $CLEANFILES
	rm magnetic
